language: c
sudo: required
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

script: ./bootstrap && ./configure && make && make -C examples
