language: c
dist: xenial
sudo: required
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev

script: ./bootstrap && ./configure && make && make -C examples
