language: c
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

script: ./bootstrap && ./configure && make
